### ISSUE TITLE
how about a snapshot release?

### ISSUE THREAD

**Issue by SmoothieAq** [ncsaba/idea-openscad#24]
I would love to use it with my IntelliJ, but it seams the current IntelliJ does now work with 1.3.0.
Could you perhaps do a quick release of the current code? I appears from the commit comments that it might work with a new IntelliJ, and also that nice new stuff have been added.
Thanks! :-)

**Comment by jesperldk** [comment]
ok, was easy enough to download, build and install in IntelliJ.
