### ISSUE TITLE
Error in build - missing item

### ISSUE THREAD

**Issue by lqbombjack** [ncsaba/idea-openscad#25]
Hi I'm struggling to build the project.  On opening it in Intellij gradle starts collecting the various dependencies but it appears to be missing the psiviewer.

I tried removing the files from the cache to force gradle to re-download them, be this didnt solve the problem:

```
100% 15:22:34 ⌚ craig@MOPR-W150E in ~/Build-Env/openscad-plugin-for-ide
± |master ✓| → ./gradlew buildNeeded
Download https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/LATEST-EAP-SNAPSHOT/ideaIC-LATEST-EAP-SNAPSHOT.zip
Download https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/LATEST-EAP-SNAPSHOT/ideaIC-LATEST-EAP-SNAPSHOT-sources.jar
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find psiviewer/lib/searchableOptions-193-SNAPSHOT-unzipped.com.jetbrains.plugins.jar (unzipped.com.jetbrains.plugins:PsiViewer:193-SNAPSHOT).
  Searched in the following locations:
      file:/home/craig/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/52292e4f8a0ccb3ceb08bd81fd57b88923ac8e99/ideaIC-LATEST-EAP-SNAPSHOT/plugins/PsiViewer/psiviewer/lib/searchableOptions-193-SNAPSHOT.jar
      file:/home/craig/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/PsiViewer-193-SNAPSHOT/psiviewer/lib/searchableOptions-193-SNAPSHOT.jar
      file:/home/craig/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/2dae8e50d4b0508cad2e680b53414f657954f390/psiviewer/lib/searchableOptions-193-SNAPSHOT-LATEST-EAP-SNAPSHOT-unzipped.com.jetbrains.plugins.jar
> Could not find psiviewer/lib/PsiViewer-unzipped.com.jetbrains.plugins.jar (unzipped.com.jetbrains.plugins:PsiViewer:193-SNAPSHOT).
  Searched in the following locations:
      file:/home/craig/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/52292e4f8a0ccb3ceb08bd81fd57b88923ac8e99/ideaIC-LATEST-EAP-SNAPSHOT/plugins/PsiViewer/psiviewer/lib/PsiViewer.jar
      file:/home/craig/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/PsiViewer-193-SNAPSHOT/psiviewer/lib/PsiViewer.jar
      file:/home/craig/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/2dae8e50d4b0508cad2e680b53414f657954f390/psiviewer/lib/PsiViewer-LATEST-EAP-SNAPSHOT-unzipped.com.jetbrains.plugins.jar
> Could not find psiviewer/lib/searchableOptions-192.4205-EAP-CANDIDATE-SNAPSHOT-unzipped.com.jetbrains.plugins.jar (unzipped.com.jetbrains.plugins:PsiViewer:193-SNAPSHOT).
  Searched in the following locations:
      file:/home/craig/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/52292e4f8a0ccb3ceb08bd81fd57b88923ac8e99/ideaIC-LATEST-EAP-SNAPSHOT/plugins/PsiViewer/psiviewer/lib/searchableOptions-192.4205-EAP-CANDIDATE-SNAPSHOT.jar
      file:/home/craig/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/PsiViewer-193-SNAPSHOT/psiviewer/lib/searchableOptions-192.4205-EAP-CANDIDATE-SNAPSHOT.jar
      file:/home/craig/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/2dae8e50d4b0508cad2e680b53414f657954f390/psiviewer/lib/searchableOptions-192.4205-EAP-CANDIDATE-SNAPSHOT-LATEST-EAP-SNAPSHOT-unzipped.com.jetbrains.plugins.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 47s
1 actionable task: 1 executed
```
Is there something I'm missing about installing the dependencies?

**Comment by ncsaba** [comment]
Hi Craig,

I stopped working on this plugin about one year ago, tried implementing
properly the include directive but after spending a lot of time on that
it turned out to be hard (if not impossible) with current idea API. In
the meantime I started using SolidPython (a python wrapper around open-
scad) and I'm mostly editing python now, not really coding in openscad.
The idea-openscad plugin is therefore not really my first priority now,
I do have lots of other things on my todo list.

I would gladly give up the control of the plugin to somebody more
motivated !

For the particular problem you wrote - I think it is a compatibility
problem, you might need a newer/older version of IntelliJ as I think
the psiviewer should be part of the platform. I didn't build the
project for a long time now, so might be wrong on that.

I will try to find a better suited maintainer for this plugin who can
do a better job on it as me right now...

Cheers,
Csaba

**Comment by jesperldk** [comment]
I did build it today and are running it in the current community edition of IntelliJ. It builds and installs with no problems.
@ncsaba a shame you are not doing any development any more.

**Comment by ncsaba** [comment]
On Mon, 2019-12-23 at 13:26 -0800, jesperldk wrote:
> @ncsaba a shame you are not doing any development any more.

Yeah, it is a shame, but I just can't find the time right now. However
ldenisey did some work recently, I will ask him if he wants to take
over the plugin release proess as well...

I might come back at one point and do some more work too, but right now
there are other things higher priority for me.

Cheers,
Csaba

**Comment by lqbombjack** [comment]
Hi Guys,

Thank you all for the comments and thanks to @ncsaba for all your effort getting it this far.  It does appear to have been receiving some more interest of late so hopefully someone might be interested in taking on maintainer-ship.

I've tried 2019.3.1 and 2018.3 versions of Intellij (all on Linux) but these were both the Ultimate edition, perhaps I should try installing the community version alongside.  (Haven't done much Java programming, mostly I use Jetbrain's ides for PHP and C and have bought the all product license since I occasionally have to work in other languages).

If I find some time over Christmas I'll try the community edition and report back on whether it helped the situation.

Thanks,
Craig.

**Comment by ldenisey** [comment]
Hello guys,

@lqbombjack , can you try to delete line https://github.com/ncsaba/idea-openscad/blob/master/build.gradle#L20 and rebuild ?
I build successfully without PsiViewer on windows, Intellij community 2019.2.2 just now. Never tried to build on Linux.
@jesperldk : on which version/os did you build ?
Actually this plugin should not be required but it is very useful for debugging. Left it for more tests on new version.
@ncsaba, I can take ownership, let's talk about that after christmas.

**Comment by jesperldk** [comment]
I'm on Windows IntelliJ community edition 2019.3.1. I did not change anything to do the build.
@ldenisey Great if you could take ownership!
@ncsaba Thanks for the work so far! :-D

**Comment by lqbombjack** [comment]
Hi @ldenisey, yeah removing the line allowed it to build, using Itellij Ultimate 2019.3.1. on Linux.

I didn't realise it was mainly a development tool.  Good to know.

Thanks to everybody for such quick replies.  Have a good christmas / new year.
