### ISSUE TITLE
2019.05 features not fully supported

### ISSUE THREAD

**Issue by SmoothieAq** [ncsaba/idea-openscad#34]
2019.05:
» Added assert() module and assert() function
» Added let() module
» Added ord() function
» Added echo() function
» Added type testing functions: is_undef(), is_list(), is_num(), is_bool(), is_string()

Most of this does not work. I know you added the echo() function, but I think it should be a null prefix operator (like !), and assert() should be the same.
The following is a valid OpenSCAD expression, but does not parse in IntelliJ:
x = assert(true,"xx") assert(true,"yy") echo("first") echo("second") 3+3;

The current snapshot supports one echo, but not several (which I use :-), and it does not support assert() (which I also use).

This is a nasty bug, because often a single echo() or an asset() can cause code completion to stop working for most of a large OpenSCAD file.

**Comment by ldenisey** [comment]
Fixed, will be released in version 2.2.0 coming soon.
