### ISSUE TITLE
code completion does not work for nested include

### ISSUE THREAD

**Issue by SmoothieAq** [ncsaba/idea-openscad#40]
if I have aaa.scad
```
abc = 1;
```

and bbb.scad
```
include <aaa.scad>
```

and ccc.scad
```
include <bbb.scad>

echo(abc);
```

Then code completion does not work on abc in ccc.scad.

**Comment by ldenisey** [comment]
Fixed in d971edafcc8632b43af6f99746bf595225693e2b, please confirm.

**Comment by SmoothieAq** [comment]
Thanks!
I have installed it, and more works now.
I will use it for a couple of days, and then close this issue if all are well :-)

**Comment by SmoothieAq** [comment]
I had to remove this version after experiencing several total freezes of IntelliJ. After I was back to the previous version I have had no more freezes. Perhaps this is related to #42

**Comment by SmoothieAq** [comment]
I hope you can fix this - I was really nice the few minutes it did work.
I do have large project that use large libraries, so there are deep includes and use'es.

**Comment by ldenisey** [comment]
I am closing this issue as they were several fixes pushed these days. Please retry and open a new issue if you still experiment problems.
