### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by davies46** [ncsaba/idea-openscad#5]
Hello and thanks for developing this plugin - I'm a keen OpenScad user and not happy with the current editing options :)

I am using PyCharm Community 2018.1, Build #PC-181.5540.17, Aug 21 2018 (64-bit).

Install plugin from disk gives me the error message:
"Plugin 'OpenSCAD Language Support' is incompatible with this installation

From your notes it looks like this plugin should be compatible.

Thanks

**Comment by ncsaba** [comment]
As discussed per E-Mail, for the moment only the latest IntelliJ platform version is supported. The functionality is not yet at the level I'm aiming for, and I discovered some show-stopper bugs in the grammar I will need to fix before I can push a newer version with more functionality.
