### ISSUE TITLE
"include" navigation

### ISSUE THREAD

**Issue by gounthar** [ncsaba/idea-openscad#58]
Would it be possible to navigate thanks to the "include" directive with CTRL+B as we do with modules and functions?
Thanks a lot for your work.

**Comment by ldenisey** [comment]
Not sure to understand. Could you provide a simple example of what you would like ?

**Comment by mjparme** [comment]
It looks like cmd-b navigation works with the `include` directive, but not `use`. It would be nice if it worked with `use` as well.

**Comment by ldenisey** [comment]
It is working in current version. A new version is coming soon, please check if the issue still exists and submit a new issue in the new repository https://github.com/ldenisey/idea-openscad if needed.
