### ISSUE TITLE
nested conditional ? does not parse correctly

### ISSUE THREAD

**Issue by SmoothieAq** [ncsaba/idea-openscad#60]
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Conditional_and_Iterator_Functions#Conditional_?_:

a = 4;
echo( a > 2 ? a < 3 ? "1" : "2" : "3" );

does not parse.

**Comment by ldenisey** [comment]
Fixed, will be released in version 2.2.0 coming soon.
