### ISSUE TITLE
Doesn't open app correctly if file path includes spaces

### ISSUE THREAD

**Issue by C06A** [ncsaba/idea-openscad#62]
For application itself, if path includes the spaces, then whole path included in double quotes. So application starts successfully.

However if the path to the .scad file includes spaces the application opens no file. To fix this the path to the file must be included in the double quotes (or each space should be prepended by back-slash ("\").

**Comment by ldenisey** [comment]
Thank you for your feedback, solved in #64 . You can test it from master build as of now or wait for version 2.1.0 that should come in a few days.
