### ISSUE TITLE
OpenSCAD allows variable names to start with a number but the plugin marks it as an error

### ISSUE THREAD

**Issue by mjparme** [ncsaba/idea-openscad#80]
This is legal code:

```
1uSize = 19.05;
```

<img width="353" alt="Screen Shot 2021-08-14 at 11 38 40 AM" src="https://user-images.githubusercontent.com/1580996/129453243-e4d17173-66f0-49bf-8d80-41bfdc437e5f.png">

**Comment by mjparme** [comment]
Actually it only seems to marking this particular one as an error. If I have a variable name start with a number anywhere else it seems fine.

<img width="380" alt="Screen Shot 2021-08-14 at 11 43 08 AM" src="https://user-images.githubusercontent.com/1580996/129453326-65988982-b308-4f55-ab81-da4e24e31f6a.png">

**Comment by mjparme** [comment]
Here is a popup showing what it is complaining about:

<img width="712" alt="Screen Shot 2021-08-14 at 11 41 18 AM" src="https://user-images.githubusercontent.com/1580996/129453336-dc2fb03d-fa1b-4c5a-8a29-3db65de7c43a.png">

**Comment by ldenisey** [comment]
Fixed, will be released in version 2.2.0 coming soon.
