### ISSUE TITLE
Please add variable name completion

### ISSUE THREAD

**Issue by mjparme** [ncsaba/idea-openscad#81]
The plugin doesn't seem to offer any kind of variable name completion, that would be awesome if it did.

<img width="252" alt="Screen Shot 2021-08-14 at 11 50 19 AM" src="https://user-images.githubusercontent.com/1580996/129453497-19f5804d-469f-4d03-86ee-c31570574aba.png">

**Comment by ldenisey** [comment]
It is working in current version. A new version is coming soon, please check if the issue still exists and submit a new issue in the new repository https://github.com/ldenisey/idea-openscad if needed.
