### ISSUE TITLE
Please add module name completion

### ISSUE THREAD

**Issue by mjparme** [ncsaba/idea-openscad#82]
The plugin doesn't seem to offer any completions for modules in the current file. I am getting some completions from other files in my project (although the ones I am getting completions for aren't in a use or include directive). Would be awesome if it would offer completions for user-defined modules in the current file.

<img width="705" alt="Screen Shot 2021-08-14 at 11 53 10 AM" src="https://user-images.githubusercontent.com/1580996/129453584-a61e8121-4a36-4b1a-83ae-3e2cfc58586f.png">

**Comment by ldenisey** [comment]
It is working in current version. A new version is coming soon, please check if the issue still exists and submit a new issue in the new repository https://github.com/ldenisey/idea-openscad if needed.

**Comment by mjparme** [comment]
@ldenisey glad to see some life in this plugin. Your fork doesn't have Issues enabled so no one will be able to open an issue in your repository.

**Comment by ldenisey** [comment]
Thanks, it is activated now. Migration will be effective with next release.
