### ISSUE TITLE
Backspace in empty line not working

### ISSUE THREAD

**Issue by derlucas** [ncsaba/idea-openscad#86]
When editing an openscad file i can not remove empty lines with backspace. I have to use Ctrl+X.
I also can not remove indentation in empty lines. I have to navigate with cursor keys and remove chars that way.
Is there a way around? Other files in IDEA do not have this issue.

**Comment by ldenisey** [comment]
It should work. It is working on my test platform, I will need more detail to reproduce it.

I am migrating the project. Please create a new issue in https://github.com/ldenisey/idea-openscad with more details : OS, plateform and version, version of the plugin and full text snippet.
