### ISSUE TITLE
[bug] "include" can be included in a block object

### ISSUE THREAD

**Issue by danielsan80** [ncsaba/idea-openscad#91]
Hi, 
first of all thanks for your work.

The plugin show me an error when I try to include the "include" keyword in a block object.

Example:

```
module vase1() {
    include <modules/vase.scad>
    vase_h = 20;
    vase_h = 15;

    vase();
}

module vase2() {
    include <modules/vase.scad>
    vase_h = 10;
    vase_h = 15;

    translate([30,0,0])
    vase();
}

vase1();
vase2();
```

I'm not sure this is a good practice but OpenSCAD allow you to do that and I think it is a good way to make private a global scope without editing the included file.

**Comment by ldenisey** [comment]
Fixed, will be released in version 2.2.0 coming soon.
