### ISSUE TITLE
[request] Code style: can format cascade transformations

### ISSUE THREAD

**Issue by danielsan80** [ncsaba/idea-openscad#92]
I'd like to set a formatting preference on cascade transformations.

Generally I use this style:
```
render()
color("red")
rotate([0,45,0])
translate([20,20,20])
cube([10,10,10])

color("green")
translate([10,10,10]
sphere(r=10);
```
becaouse is more readable (for me) in the native editor.

BUT the autoformatter applies this style:
```
render()
   color("red")
      rotate([0,45,0])
         translate([20,20,20])
            cube([10,10,10])

color("green")
   translate([10,10,10]
      sphere(r=10);
```
that is nicer in PhpStorm but less readable in the native editor.

**Comment by ldenisey** [comment]
Added a field "Indent cascading transformations" in Settings menu -> Editor -> Code style -> OpenSCAD -> Tabs and Indents.
![Capture d’écran 2022-07-25 120646](https://user-images.githubusercontent.com/39246034/180753098-0d5842a7-8ccd-40ba-b7e8-e6856ff6c87b.png)
![Capture d’écran 2022-07-25 120715](https://user-images.githubusercontent.com/39246034/180753111-33f326fd-cabd-4081-bbe8-b35699f26654.png)

Will be released in version 2.2.0 coming soon.
